module DeepCopyVegetationMod
  use elm_varctl, only : use_cn
  use vegetationtype,only: vegetation_physical_properties
  use vegetationpropertiestype,only: vegetation_properties_type
  use vegetationdatatype,only: vegetation_energy_state
  use vegetationdatatype,only: vegetation_water_state
  use vegetationdatatype,only: vegetation_carbon_state
  use vegetationdatatype,only: vegetation_phosphorus_flux
  use vegetationdatatype,only: vegetation_nitrogen_state
  use vegetationdatatype,only: vegetation_phosphorus_state
  use vegetationdatatype,only: vegetation_energy_flux
  use vegetationdatatype,only: vegetation_water_flux
  use vegetationdatatype,only: vegetation_carbon_flux
  use vegetationdatatype,only: vegetation_nitrogen_flux
  implicit none
  public :: deepcopy_vegetation_physical_properties
  public :: deepcopy_vegetation_properties_type
  public :: deepcopy_vegetation_energy_state
  public :: deepcopy_vegetation_energy_flux
  public :: deepcopy_vegetation_water_state
  public :: deepcopy_vegetation_water_flux
  public :: deepcopy_vegetation_carbon_state
  public :: deepcopy_vegetation_carbon_flux
  public :: deepcopy_vegetation_phosphorus_state
  public :: deepcopy_vegetation_phosphorus_flux
  public :: deepcopy_vegetation_nitrogen_state
  public :: deepcopy_vegetation_nitrogen_flux
contains
  subroutine deepcopy_vegetation_types(veg_pp, veg_vp,veg_es,veg_ef, &
                                      veg_ws, veg_wf, veg_cs, veg_cf, &
                                      veg_ps, veg_pf, veg_ns, veg_nf)
    type(vegetation_physical_properties), intent(inout) :: veg_pp
    type(vegetation_properties_type), intent(inout) :: veg_vp
    type(vegetation_energy_state), intent(inout) :: veg_es
    type(vegetation_energy_flux), intent(inout) :: veg_ef
    type(vegetation_water_state), intent(inout) :: veg_ws
    type(vegetation_water_flux), intent(inout) :: veg_wf
    type(vegetation_carbon_state), intent(inout) :: veg_cs
    type(vegetation_carbon_flux), intent(inout) :: veg_cf
    type(vegetation_phosphorus_state), intent(inout) :: veg_ps
    type(vegetation_phosphorus_flux), intent(inout) :: veg_pf
    type(vegetation_nitrogen_state), intent(inout) :: veg_ns
    type(vegetation_nitrogen_flux), intent(inout) :: veg_nf

    call deepcopy_vegetation_physical_properties(veg_pp)
    call deepcopy_vegetation_properties_type(veg_vp)

    call deepcopy_vegetation_energy_state(veg_es)
    call deepcopy_vegetation_energy_flux(veg_ef)
    call deepcopy_vegetation_water_state(veg_ws)
    call deepcopy_vegetation_water_flux(veg_wf)

    if (use_cn) then 
      call deepcopy_vegetation_carbon_state(veg_cs)
      call deepcopy_vegetation_carbon_flux(veg_cf)
      call deepcopy_vegetation_phosphorus_state(veg_ps)
      call deepcopy_vegetation_phosphorus_flux(veg_pf)
      call deepcopy_vegetation_nitrogen_state(veg_ns)
      call deepcopy_vegetation_nitrogen_flux(veg_nf)
    end if 
  end subroutine deepcopy_vegetation_types

  subroutine deepcopy_vegetation_physical_properties(this_type)
    type(vegetation_physical_properties), intent(inout) :: this_type
    !$acc enter data copyin(this_type)
    !$acc enter data copyin(&
    !$acc& this_type%gridcell(:),&
    !$acc& this_type%wtgcell(:),&
    !$acc& this_type%topounit(:),&
    !$acc& this_type%wttopounit(:),&
    !$acc& this_type%landunit(:),&
    !$acc& this_type%wtlunit(:),&
    !$acc& this_type%column(:),&
    !$acc& this_type%wtcol(:),&
    !$acc& this_type%itype(:),&
    !$acc& this_type%mxy(:),&
    !$acc& this_type%active(:),&
    !$acc& this_type%is_fates(:),&
    !$acc& this_type%is_veg(:),&
    !$acc& this_type%is_bareground(:),&
    !$acc& this_type%wt_ed(:),&
    !$acc& this_type%sp_pftorder_index(:))
  end subroutine deepcopy_vegetation_physical_properties
  subroutine deepcopy_vegetation_properties_type(this_type)
    type(vegetation_properties_type), intent(inout) :: this_type
    !$acc enter data copyin(this_type)
    !$acc enter data copyin(&
    !$acc& this_type%noveg(:),&
    !$acc& this_type%tree(:),&
    !$acc& this_type%smpso(:),&
    !$acc& this_type%smpsc(:),&
    !$acc& this_type%fnitr(:),&
    !$acc& this_type%foln(:),&
    !$acc& this_type%dleaf(:),&
    !$acc& this_type%c3psn(:),&
    !$acc& this_type%xl(:),&
    !$acc& this_type%rhol(:,:),&
    !$acc& this_type%rhos(:,:),&
    !$acc& this_type%taul(:,:),&
    !$acc& this_type%taus(:,:),&
    !$acc& this_type%z0mr(:),&
    !$acc& this_type%displar(:),&
    !$acc& this_type%roota_par(:),&
    !$acc& this_type%rootb_par(:),&
    !$acc& this_type%slatop(:),&
    !$acc& this_type%dsladlai(:),&
    !$acc& this_type%leafcn(:),&
    !$acc& this_type%flnr(:),&
    !$acc& this_type%woody(:),&
    !$acc& this_type%lflitcn(:),&
    !$acc& this_type%frootcn(:),&
    !$acc& this_type%livewdcn(:),&
    !$acc& this_type%deadwdcn(:),&
    !$acc& this_type%graincn(:),&
    !$acc& this_type%froot_leaf(:),&
    !$acc& this_type%stem_leaf(:),&
    !$acc& this_type%croot_stem(:),&
    !$acc& this_type%flivewd(:),&
    !$acc& this_type%fcur(:),&
    !$acc& this_type%lf_flab(:),&
    !$acc& this_type%lf_fcel(:),&
    !$acc& this_type%lf_flig(:),&
    !$acc& this_type%fr_flab(:),&
    !$acc& this_type%fr_fcel(:),&
    !$acc& this_type%fr_flig(:),&
    !$acc& this_type%leaf_long(:),&
    !$acc& this_type%froot_long(:),&
    !$acc& this_type%evergreen(:),&
    !$acc& this_type%stress_decid(:),&
    !$acc& this_type%season_decid(:),&
    !$acc& this_type%dwood(:),&
    !$acc& this_type%root_radius(:),&
    !$acc& this_type%root_density(:),&
    !$acc& this_type%rootprof_beta(:),&
    !$acc& this_type%fertnitro(:),&
    !$acc& this_type%fleafcn(:),&
    !$acc& this_type%ffrootcn(:),&
    !$acc& this_type%fstemcn(:),&
    !$acc& this_type%presharv(:),&
    !$acc& this_type%convfact(:),&
    !$acc& this_type%fyield(:),&
    !$acc& this_type%leafcp(:),&
    !$acc& this_type%lflitcp(:),&
    !$acc& this_type%frootcp(:),&
    !$acc& this_type%livewdcp(:),&
    !$acc& this_type%deadwdcp(:),&
    !$acc& this_type%graincp(:),&
    !$acc& this_type%alpha_nfix(:),&
    !$acc& this_type%alpha_ptase(:),&
    !$acc& this_type%ccost_nfix(:),&
    !$acc& this_type%ccost_ptase(:),&
    !$acc& this_type%vmax_plant_nh4(:),&
    !$acc& this_type%vmax_plant_no3(:),&
    !$acc& this_type%vmax_plant_p(:),&
    !$acc& this_type%vmax_minsurf_p_vr(:,:),&
    !$acc& this_type%km_plant_nh4(:),&
    !$acc& this_type%km_plant_no3(:),&
    !$acc& this_type%km_plant_p(:),&
    !$acc& this_type%km_minsurf_p_vr(:,:),&
    !$acc& this_type%decompmicc_patch_vr(:,:),&
    !$acc& this_type%vmax_ptase(:),&
    !$acc& this_type%i_vc(:),&
    !$acc& this_type%s_vc(:),&
    !$acc& this_type%nsc_rtime(:),&
    !$acc& this_type%pinit_beta1(:),&
    !$acc& this_type%pinit_beta2(:),&
    !$acc& this_type%vmax_nfix(:),&
    !$acc& this_type%km_nfix(:),&
    !$acc& this_type%fnr(:),&
    !$acc& this_type%act25(:),&
    !$acc& this_type%kcha(:),&
    !$acc& this_type%koha(:),&
    !$acc& this_type%cpha(:),&
    !$acc& this_type%vcmaxha(:),&
    !$acc& this_type%jmaxha(:),&
    !$acc& this_type%tpuha(:),&
    !$acc& this_type%lmrha(:),&
    !$acc& this_type%vcmaxhd(:),&
    !$acc& this_type%jmaxhd(:),&
    !$acc& this_type%tpuhd(:),&
    !$acc& this_type%lmrhd(:),&
    !$acc& this_type%lmrse(:),&
    !$acc& this_type%qe(:),&
    !$acc& this_type%theta_cj(:),&
    !$acc& this_type%bbbopt(:),&
    !$acc& this_type%mbbopt(:),&
    !$acc& this_type%nstor(:),&
    !$acc& this_type%br_xr(:),&
    !$acc& this_type%km_decomp_nh4,&
    !$acc& this_type%km_decomp_no3,&
    !$acc& this_type%km_decomp_p,&
    !$acc& this_type%km_nit,&
    !$acc& this_type%km_den,&
    !$acc& this_type%km_ptase,&
    !$acc& this_type%lamda_ptase,&
    !$acc& this_type%tc_stress)
  end subroutine deepcopy_vegetation_properties_type
  subroutine deepcopy_vegetation_energy_state(this_type)
    type(vegetation_energy_state), intent(inout) :: this_type
    !$acc enter data copyin(this_type)
    !$acc enter data copyin(&
    !$acc& this_type%t_veg(:),&
    !$acc& this_type%t_ref2m(:),&
    !$acc& this_type%t_ref2m_r(:),&
    !$acc& this_type%t_ref2m_u(:),&
    !$acc& this_type%t_a10(:),&
    !$acc& this_type%t_a10min(:),&
    !$acc& this_type%t_a5min(:),&
    !$acc& this_type%t_ref2m_min(:),&
    !$acc& this_type%t_ref2m_min_r(:),&
    !$acc& this_type%t_ref2m_min_u(:),&
    !$acc& this_type%t_ref2m_max(:),&
    !$acc& this_type%t_ref2m_max_r(:),&
    !$acc& this_type%t_ref2m_max_u(:),&
    !$acc& this_type%t_ref2m_min_inst(:),&
    !$acc& this_type%t_ref2m_min_inst_r(:),&
    !$acc& this_type%t_ref2m_min_inst_u(:),&
    !$acc& this_type%t_ref2m_max_inst(:),&
    !$acc& this_type%t_ref2m_max_inst_r(:),&
    !$acc& this_type%t_ref2m_max_inst_u(:),&
    !$acc& this_type%t_veg24(:),&
    !$acc& this_type%t_veg240(:),&
    !$acc& this_type%gdd0(:),&
    !$acc& this_type%gdd8(:),&
    !$acc& this_type%gdd10(:),&
    !$acc& this_type%gdd020(:),&
    !$acc& this_type%gdd820(:),&
    !$acc& this_type%gdd1020(:),&
    !$acc& this_type%thm(:),&
    !$acc& this_type%emv(:))
  end subroutine deepcopy_vegetation_energy_state
  subroutine deepcopy_vegetation_water_state(this_type)
    type(vegetation_water_state), intent(inout) :: this_type
    !$acc enter data copyin(this_type)
    !$acc enter data copyin(&
    !$acc& this_type%h2ocan(:),&
    !$acc& this_type%q_ref2m(:),&
    !$acc& this_type%rh_ref2m(:),&
    !$acc& this_type%rh_ref2m_r(:),&
    !$acc& this_type%rh_ref2m_u(:),&
    !$acc& this_type%rh_af(:),&
    !$acc& this_type%fwet(:),&
    !$acc& this_type%fdry(:),&
    !$acc& this_type%begwb(:),&
    !$acc& this_type%endwb(:),&
    !$acc& this_type%errh2o(:))
  end subroutine deepcopy_vegetation_water_state
  subroutine deepcopy_vegetation_carbon_state(this_type)
    type(vegetation_carbon_state), intent(inout) :: this_type
    !$acc enter data copyin(this_type)
    !$acc enter data copyin(&
    !$acc& this_type%leafc(:),&
    !$acc& this_type%leafc_storage(:),&
    !$acc& this_type%leafc_xfer(:),&
    !$acc& this_type%frootc(:),&
    !$acc& this_type%frootc_storage(:),&
    !$acc& this_type%frootc_xfer(:),&
    !$acc& this_type%livestemc(:),&
    !$acc& this_type%livestemc_storage(:),&
    !$acc& this_type%livestemc_xfer(:),&
    !$acc& this_type%deadstemc(:),&
    !$acc& this_type%deadstemc_storage(:),&
    !$acc& this_type%deadstemc_xfer(:),&
    !$acc& this_type%livecrootc(:),&
    !$acc& this_type%livecrootc_storage(:),&
    !$acc& this_type%livecrootc_xfer(:),&
    !$acc& this_type%deadcrootc(:),&
    !$acc& this_type%deadcrootc_storage(:),&
    !$acc& this_type%deadcrootc_xfer(:),&
    !$acc& this_type%gresp_storage(:),&
    !$acc& this_type%gresp_xfer(:),&
    !$acc& this_type%cpool(:),&
    !$acc& this_type%xsmrpool(:),&
    !$acc& this_type%ctrunc(:),&
    !$acc& this_type%dispvegc(:),&
    !$acc& this_type%storvegc(:),&
    !$acc& this_type%totvegc(:),&
    !$acc& this_type%totpftc(:),&
    !$acc& this_type%leafcmax(:),&
    !$acc& this_type%grainc(:),&
    !$acc& this_type%grainc_storage(:),&
    !$acc& this_type%grainc_xfer(:),&
    !$acc& this_type%woodc(:),&
    !$acc& this_type%totvegc_abg(:),&
    !$acc& this_type%begcb(:),&
    !$acc& this_type%endcb(:),&
    !$acc& this_type%errcb(:),&
    !$acc& this_type%cropseedc_deficit(:),&
    !$acc& this_type%species)
  end subroutine deepcopy_vegetation_carbon_state
  subroutine deepcopy_vegetation_phosphorus_flux(this_type)
    type(vegetation_phosphorus_flux), intent(inout) :: this_type
    !$acc enter data copyin(this_type)
    !$acc enter data copyin(&
    !$acc& this_type%m_leafp_to_litter(:),&
    !$acc& this_type%m_frootp_to_litter(:),&
    !$acc& this_type%m_leafp_storage_to_litter(:),&
    !$acc& this_type%m_frootp_storage_to_litter(:),&
    !$acc& this_type%m_livestemp_storage_to_litter(:),&
    !$acc& this_type%m_deadstemp_storage_to_litter(:),&
    !$acc& this_type%m_livecrootp_storage_to_litter(:),&
    !$acc& this_type%m_deadcrootp_storage_to_litter(:),&
    !$acc& this_type%m_leafp_xfer_to_litter(:),&
    !$acc& this_type%m_frootp_xfer_to_litter(:),&
    !$acc& this_type%m_livestemp_xfer_to_litter(:),&
    !$acc& this_type%m_deadstemp_xfer_to_litter(:),&
    !$acc& this_type%m_livecrootp_xfer_to_litter(:),&
    !$acc& this_type%m_deadcrootp_xfer_to_litter(:),&
    !$acc& this_type%m_livestemp_to_litter(:),&
    !$acc& this_type%m_deadstemp_to_litter(:),&
    !$acc& this_type%m_livecrootp_to_litter(:),&
    !$acc& this_type%m_deadcrootp_to_litter(:),&
    !$acc& this_type%m_retransp_to_litter(:),&
    !$acc& this_type%m_ppool_to_litter(:),&
    !$acc& this_type%hrv_leafp_to_litter(:),&
    !$acc& this_type%hrv_frootp_to_litter(:),&
    !$acc& this_type%hrv_leafp_storage_to_litter(:),&
    !$acc& this_type%hrv_frootp_storage_to_litter(:),&
    !$acc& this_type%hrv_livestemp_storage_to_litter(:),&
    !$acc& this_type%hrv_deadstemp_storage_to_litter(:),&
    !$acc& this_type%hrv_livecrootp_storage_to_litter(:),&
    !$acc& this_type%hrv_deadcrootp_storage_to_litter(:),&
    !$acc& this_type%hrv_leafp_xfer_to_litter(:),&
    !$acc& this_type%hrv_frootp_xfer_to_litter(:),&
    !$acc& this_type%hrv_livestemp_xfer_to_litter(:),&
    !$acc& this_type%hrv_deadstemp_xfer_to_litter(:),&
    !$acc& this_type%hrv_livecrootp_xfer_to_litter(:),&
    !$acc& this_type%hrv_deadcrootp_xfer_to_litter(:),&
    !$acc& this_type%hrv_livestemp_to_litter(:),&
    !$acc& this_type%hrv_deadstemp_to_prod10p(:),&
    !$acc& this_type%hrv_deadstemp_to_prod100p(:),&
    !$acc& this_type%hrv_leafp_to_prod1p(:),&
    !$acc& this_type%hrv_livestemp_to_prod1p(:),&
    !$acc& this_type%hrv_grainp_to_prod1p(:),&
    !$acc& this_type%hrv_cropp_to_prod1p(:),&
    !$acc& this_type%hrv_livecrootp_to_litter(:),&
    !$acc& this_type%hrv_deadcrootp_to_litter(:),&
    !$acc& this_type%hrv_retransp_to_litter(:),&
    !$acc& this_type%hrv_ppool_to_litter(:),&
    !$acc& this_type%m_leafp_to_fire(:),&
    !$acc& this_type%m_leafp_storage_to_fire(:),&
    !$acc& this_type%m_leafp_xfer_to_fire(:),&
    !$acc& this_type%m_livestemp_to_fire(:),&
    !$acc& this_type%m_livestemp_storage_to_fire(:),&
    !$acc& this_type%m_livestemp_xfer_to_fire(:),&
    !$acc& this_type%m_deadstemp_to_fire(:),&
    !$acc& this_type%m_deadstemp_storage_to_fire(:),&
    !$acc& this_type%m_deadstemp_xfer_to_fire(:),&
    !$acc& this_type%m_frootp_to_fire(:),&
    !$acc& this_type%m_frootp_storage_to_fire(:),&
    !$acc& this_type%m_frootp_xfer_to_fire(:),&
    !$acc& this_type%m_livecrootp_to_fire(:),&
    !$acc& this_type%m_livecrootp_storage_to_fire(:),&
    !$acc& this_type%m_livecrootp_xfer_to_fire(:),&
    !$acc& this_type%m_deadcrootp_to_fire(:),&
    !$acc& this_type%m_deadcrootp_storage_to_fire(:),&
    !$acc& this_type%m_deadcrootp_xfer_to_fire(:),&
    !$acc& this_type%m_retransp_to_fire(:),&
    !$acc& this_type%m_ppool_to_fire(:),&
    !$acc& this_type%m_leafp_to_litter_fire(:),&
    !$acc& this_type%m_leafp_storage_to_litter_fire(:),&
    !$acc& this_type%m_leafp_xfer_to_litter_fire(:),&
    !$acc& this_type%m_livestemp_to_litter_fire(:),&
    !$acc& this_type%m_livestemp_storage_to_litter_fire(:),&
    !$acc& this_type%m_livestemp_xfer_to_litter_fire(:),&
    !$acc& this_type%m_livestemp_to_deadstemp_fire(:),&
    !$acc& this_type%m_deadstemp_to_litter_fire(:),&
    !$acc& this_type%m_deadstemp_storage_to_litter_fire(:),&
    !$acc& this_type%m_deadstemp_xfer_to_litter_fire(:),&
    !$acc& this_type%m_frootp_to_litter_fire(:),&
    !$acc& this_type%m_frootp_storage_to_litter_fire(:),&
    !$acc& this_type%m_frootp_xfer_to_litter_fire(:),&
    !$acc& this_type%m_livecrootp_to_litter_fire(:),&
    !$acc& this_type%m_livecrootp_storage_to_litter_fire(:),&
    !$acc& this_type%m_livecrootp_xfer_to_litter_fire(:),&
    !$acc& this_type%m_livecrootp_to_deadcrootp_fire(:),&
    !$acc& this_type%m_deadcrootp_to_litter_fire(:),&
    !$acc& this_type%m_deadcrootp_storage_to_litter_fire(:),&
    !$acc& this_type%m_deadcrootp_xfer_to_litter_fire(:),&
    !$acc& this_type%m_retransp_to_litter_fire(:),&
    !$acc& this_type%m_ppool_to_litter_fire(:),&
    !$acc& this_type%leafp_xfer_to_leafp(:),&
    !$acc& this_type%frootp_xfer_to_frootp(:),&
    !$acc& this_type%livestemp_xfer_to_livestemp(:),&
    !$acc& this_type%deadstemp_xfer_to_deadstemp(:),&
    !$acc& this_type%livecrootp_xfer_to_livecrootp(:),&
    !$acc& this_type%deadcrootp_xfer_to_deadcrootp(:),&
    !$acc& this_type%leafp_to_litter(:),&
    !$acc& this_type%leafp_to_retransp(:),&
    !$acc& this_type%frootp_to_retransp(:),&
    !$acc& this_type%frootp_to_litter(:),&
    !$acc& this_type%retransp_to_ppool(:),&
    !$acc& this_type%sminp_to_ppool(:),&
    !$acc& this_type%biochem_pmin_to_plant(:),&
    !$acc& this_type%ppool_to_leafp(:),&
    !$acc& this_type%ppool_to_leafp_storage(:),&
    !$acc& this_type%ppool_to_frootp(:),&
    !$acc& this_type%ppool_to_frootp_storage(:),&
    !$acc& this_type%ppool_to_livestemp(:),&
    !$acc& this_type%ppool_to_livestemp_storage(:),&
    !$acc& this_type%ppool_to_deadstemp(:),&
    !$acc& this_type%ppool_to_deadstemp_storage(:),&
    !$acc& this_type%ppool_to_livecrootp(:),&
    !$acc& this_type%ppool_to_livecrootp_storage(:),&
    !$acc& this_type%ppool_to_deadcrootp(:),&
    !$acc& this_type%ppool_to_deadcrootp_storage(:),&
    !$acc& this_type%leafp_storage_to_xfer(:),&
    !$acc& this_type%frootp_storage_to_xfer(:),&
    !$acc& this_type%livestemp_storage_to_xfer(:),&
    !$acc& this_type%deadstemp_storage_to_xfer(:),&
    !$acc& this_type%livecrootp_storage_to_xfer(:),&
    !$acc& this_type%deadcrootp_storage_to_xfer(:),&
    !$acc& this_type%livestemp_to_deadstemp(:),&
    !$acc& this_type%livestemp_to_retransp(:),&
    !$acc& this_type%livecrootp_to_deadcrootp(:),&
    !$acc& this_type%livecrootp_to_retransp(:),&
    !$acc& this_type%pdeploy(:),&
    !$acc& this_type%wood_harvestp(:),&
    !$acc& this_type%fire_ploss(:),&
    !$acc& this_type%ppool_to_grainp(:),&
    !$acc& this_type%ppool_to_grainp_storage(:),&
    !$acc& this_type%livestemp_to_litter(:),&
    !$acc& this_type%grainp_to_food(:),&
    !$acc& this_type%grainp_xfer_to_grainp(:),&
    !$acc& this_type%grainp_storage_to_xfer(:),&
    !$acc& this_type%fert_p(:),&
    !$acc& this_type%fert_p_counter(:),&
    !$acc& this_type%crop_seedp_to_leaf(:),&
    !$acc& this_type%dwt_seedp_to_leaf(:),&
    !$acc& this_type%dwt_seedp_to_deadstem(:),&
    !$acc& this_type%dwt_conv_pflux(:),&
    !$acc& this_type%dwt_prod10p_gain(:),&
    !$acc& this_type%dwt_prod100p_gain(:),&
    !$acc& this_type%dwt_crop_productp_gain(:),&
    !$acc& this_type%dwt_seedp_to_ppool(:),&
    !$acc& this_type%plant_pdemand(:),&
    !$acc& this_type%avail_retransp(:),&
    !$acc& this_type%plant_palloc(:),&
    !$acc& this_type%sminp_to_plant(:),&
    !$acc& this_type%plant_pdemand_vr(:,:),&
    !$acc& this_type%prev_leafp_to_litter(:),&
    !$acc& this_type%prev_frootp_to_litter(:),&
    !$acc& this_type%supplement_to_plantp(:),&
    !$acc& this_type%gap_ploss_litter(:),&
    !$acc& this_type%fire_ploss_litter(:),&
    !$acc& this_type%hrv_ploss_litter(:),&
    !$acc& this_type%sen_ploss_litter(:))
  end subroutine deepcopy_vegetation_phosphorus_flux
  subroutine deepcopy_vegetation_nitrogen_state(this_type)
    type(vegetation_nitrogen_state), intent(inout) :: this_type
    !$acc enter data copyin(this_type)
    !$acc enter data copyin(&
    !$acc& this_type%leafn(:),&
    !$acc& this_type%leafn_storage(:),&
    !$acc& this_type%leafn_xfer(:),&
    !$acc& this_type%frootn(:),&
    !$acc& this_type%frootn_storage(:),&
    !$acc& this_type%frootn_xfer(:),&
    !$acc& this_type%livestemn(:),&
    !$acc& this_type%livestemn_storage(:),&
    !$acc& this_type%livestemn_xfer(:),&
    !$acc& this_type%deadstemn(:),&
    !$acc& this_type%deadstemn_storage(:),&
    !$acc& this_type%deadstemn_xfer(:),&
    !$acc& this_type%livecrootn(:),&
    !$acc& this_type%livecrootn_storage(:),&
    !$acc& this_type%livecrootn_xfer(:),&
    !$acc& this_type%deadcrootn(:),&
    !$acc& this_type%deadcrootn_storage(:),&
    !$acc& this_type%deadcrootn_xfer(:),&
    !$acc& this_type%retransn(:),&
    !$acc& this_type%npool(:),&
    !$acc& this_type%ntrunc(:),&
    !$acc& this_type%plant_n_buffer(:),&
    !$acc& this_type%grainn(:),&
    !$acc& this_type%grainn_storage(:),&
    !$acc& this_type%grainn_xfer(:),&
    !$acc& this_type%cropseedn_deficit(:),&
    !$acc& this_type%dispvegn(:),&
    !$acc& this_type%storvegn(:),&
    !$acc& this_type%totvegn(:),&
    !$acc& this_type%totpftn(:),&
    !$acc& this_type%begnb(:),&
    !$acc& this_type%endnb(:),&
    !$acc& this_type%errnb(:),&
    !$acc& this_type%npimbalance(:),&
    !$acc& this_type%pnup_pfrootc(:),&
    !$acc& this_type%ppup_pfrootc(:),&
    !$acc& this_type%ptlai_pleafc(:),&
    !$acc& this_type%ppsnsun_ptlai(:),&
    !$acc& this_type%ppsnsun_pleafn(:),&
    !$acc& this_type%ppsnsun_pleafp(:),&
    !$acc& this_type%plmrsun_ptlai(:),&
    !$acc& this_type%plmrsun_pleafn(:),&
    !$acc& this_type%plaisun_ptlai(:),&
    !$acc& this_type%ppsnsha_ptlai(:),&
    !$acc& this_type%ppsnsha_pleafn(:),&
    !$acc& this_type%ppsnsha_pleafp(:),&
    !$acc& this_type%plmrsha_ptlai(:),&
    !$acc& this_type%plmrsha_pleafn(:),&
    !$acc& this_type%plaisha_ptlai(:),&
    !$acc& this_type%benefit_pgpp_pleafc(:),&
    !$acc& this_type%benefit_pgpp_pleafn(:),&
    !$acc& this_type%benefit_pgpp_pleafp(:),&
    !$acc& this_type%cost_pgpp_pfrootc(:),&
    !$acc& this_type%cost_plmr_pleafc(:),&
    !$acc& this_type%cost_plmr_pleafn(:),&
    !$acc& this_type%ppsn_ptlai_z(:,:),&
    !$acc& this_type%ppsn_pleafn_z(:,:),&
    !$acc& this_type%ppsn_pleafp_z(:,:),&
    !$acc& this_type%ppsn_ptlai_z_vcmax(:,:),&
    !$acc& this_type%ppsn_pleafn_z_vcmax(:,:),&
    !$acc& this_type%ppsn_pleafp_z_vcmax(:,:),&
    !$acc& this_type%ppsn_ptlai_z_jmax(:,:),&
    !$acc& this_type%ppsn_pleafn_z_jmax(:,:),&
    !$acc& this_type%ppsn_pleafp_z_jmax(:,:),&
    !$acc& this_type%ppsn_ptlai_z_tpu(:,:),&
    !$acc& this_type%ppsn_pleafn_z_tpu(:,:),&
    !$acc& this_type%ppsn_pleafp_z_tpu(:,:),&
    !$acc& this_type%plmr_ptlai_z(:,:),&
    !$acc& this_type%plmr_pleafn_z(:,:))
  end subroutine deepcopy_vegetation_nitrogen_state
  subroutine deepcopy_vegetation_phosphorus_state(this_type)
    type(vegetation_phosphorus_state), intent(inout) :: this_type
    !$acc enter data copyin(this_type)
    !$acc enter data copyin(&
    !$acc& this_type%grainp(:),&
    !$acc& this_type%grainp_storage(:),&
    !$acc& this_type%grainp_xfer(:),&
    !$acc& this_type%leafp(:),&
    !$acc& this_type%leafp_storage(:),&
    !$acc& this_type%leafp_xfer(:),&
    !$acc& this_type%frootp(:),&
    !$acc& this_type%frootp_storage(:),&
    !$acc& this_type%frootp_xfer(:),&
    !$acc& this_type%livestemp(:),&
    !$acc& this_type%livestemp_storage(:),&
    !$acc& this_type%livestemp_xfer(:),&
    !$acc& this_type%deadstemp(:),&
    !$acc& this_type%deadstemp_storage(:),&
    !$acc& this_type%deadstemp_xfer(:),&
    !$acc& this_type%livecrootp(:),&
    !$acc& this_type%livecrootp_storage(:),&
    !$acc& this_type%livecrootp_xfer(:),&
    !$acc& this_type%deadcrootp(:),&
    !$acc& this_type%deadcrootp_storage(:),&
    !$acc& this_type%deadcrootp_xfer(:),&
    !$acc& this_type%retransp(:),&
    !$acc& this_type%ppool(:),&
    !$acc& this_type%ptrunc(:),&
    !$acc& this_type%dispvegp(:),&
    !$acc& this_type%storvegp(:),&
    !$acc& this_type%totvegp(:),&
    !$acc& this_type%totpftp(:),&
    !$acc& this_type%plant_p_buffer(:),&
    !$acc& this_type%cropseedp_deficit(:),&
    !$acc& this_type%begpb(:),&
    !$acc& this_type%endpb(:),&
    !$acc& this_type%errpb(:))
  end subroutine deepcopy_vegetation_phosphorus_state
  subroutine deepcopy_vegetation_energy_flux(this_type)
    type(vegetation_energy_flux), intent(inout) :: this_type
    !$acc enter data copyin(this_type)
    !$acc enter data copyin(&
    !$acc& this_type%eflx_sh_grnd(:),&
    !$acc& this_type%eflx_sh_veg(:),&
    !$acc& this_type%eflx_sh_snow(:),&
    !$acc& this_type%eflx_sh_soil(:),&
    !$acc& this_type%eflx_sh_h2osfc(:),&
    !$acc& this_type%eflx_sh_tot(:),&
    !$acc& this_type%eflx_sh_tot_u(:),&
    !$acc& this_type%eflx_sh_tot_r(:),&
    !$acc& this_type%eflx_lh_tot(:),&
    !$acc& this_type%eflx_lh_tot_u(:),&
    !$acc& this_type%eflx_lh_tot_r(:),&
    !$acc& this_type%eflx_lh_vegt(:),&
    !$acc& this_type%eflx_lh_vege(:),&
    !$acc& this_type%eflx_lh_grnd(:),&
    !$acc& this_type%eflx_soil_grnd(:),&
    !$acc& this_type%eflx_soil_grnd_u(:),&
    !$acc& this_type%eflx_soil_grnd_r(:),&
    !$acc& this_type%eflx_lwrad_net(:),&
    !$acc& this_type%eflx_lwrad_net_r(:),&
    !$acc& this_type%eflx_lwrad_net_u(:),&
    !$acc& this_type%eflx_lwrad_out(:),&
    !$acc& this_type%eflx_lwrad_out_r(:),&
    !$acc& this_type%eflx_lwrad_out_u(:),&
    !$acc& this_type%eflx_gnet(:),&
    !$acc& this_type%eflx_grnd_lake(:),&
    !$acc& this_type%eflx_anthro(:),&
    !$acc& this_type%eflx_traffic(:),&
    !$acc& this_type%eflx_wasteheat(:),&
    !$acc& this_type%eflx_heat_from_ac(:),&
    !$acc& this_type%dlrad(:),&
    !$acc& this_type%ulrad(:),&
    !$acc& this_type%taux(:),&
    !$acc& this_type%tauy(:),&
    !$acc& this_type%dgnetdt(:),&
    !$acc& this_type%netrad(:),&
    !$acc& this_type%cgrnd(:),&
    !$acc& this_type%cgrndl(:),&
    !$acc& this_type%cgrnds(:),&
    !$acc& this_type%errsoi(:),&
    !$acc& this_type%errseb(:),&
    !$acc& this_type%errsol(:),&
    !$acc& this_type%errlon(:))
  end subroutine deepcopy_vegetation_energy_flux
  subroutine deepcopy_vegetation_water_flux(this_type)
    type(vegetation_water_flux), intent(inout) :: this_type
    !$acc enter data copyin(this_type)
    !$acc enter data copyin(&
    !$acc& this_type%qflx_prec_grnd(:),&
    !$acc& this_type%qflx_rain_grnd(:),&
    !$acc& this_type%qflx_snow_grnd(:),&
    !$acc& this_type%qflx_sub_snow(:),&
    !$acc& this_type%qflx_evap_soi(:),&
    !$acc& this_type%qflx_evap_veg(:),&
    !$acc& this_type%qflx_evap_can(:),&
    !$acc& this_type%qflx_evap_tot(:),&
    !$acc& this_type%qflx_evap_grnd(:),&
    !$acc& this_type%qflx_snwcp_liq(:),&
    !$acc& this_type%qflx_snwcp_ice(:),&
    !$acc& this_type%qflx_tran_veg(:),&
    !$acc& this_type%qflx_dew_snow(:),&
    !$acc& this_type%qflx_dew_grnd(:),&
    !$acc& this_type%qflx_prec_intr(:),&
    !$acc& this_type%qflx_dirct_rain(:),&
    !$acc& this_type%qflx_leafdrip(:),&
    !$acc& this_type%qflx_ev_snow(:),&
    !$acc& this_type%qflx_ev_soil(:),&
    !$acc& this_type%qflx_ev_h2osfc(:),&
    !$acc& this_type%qflx_rootsoi_frac(:,:),&
    !$acc& this_type%irrig_rate(:),&
    !$acc& this_type%qflx_irrig_patch(:),&
    !$acc& this_type%qflx_real_irrig_patch(:),&
    !$acc& this_type%qflx_grnd_irrig_patch(:),&
    !$acc& this_type%qflx_surf_irrig_patch(:),&
    !$acc& this_type%qflx_supply_patch(:),&
    !$acc& this_type%qflx_over_supply_patch(:),&
    !$acc& this_type%n_irrig_steps_left(:))
  end subroutine deepcopy_vegetation_water_flux
  subroutine deepcopy_vegetation_carbon_flux(this_type)
    type(vegetation_carbon_flux), intent(inout) :: this_type
    !$acc enter data copyin(this_type)
    !$acc enter data copyin(&
    !$acc& this_type%m_leafc_to_litter(:),&
    !$acc& this_type%m_leafc_storage_to_litter(:),&
    !$acc& this_type%m_leafc_xfer_to_litter(:),&
    !$acc& this_type%m_frootc_to_litter(:),&
    !$acc& this_type%m_frootc_storage_to_litter(:),&
    !$acc& this_type%m_frootc_xfer_to_litter(:),&
    !$acc& this_type%m_livestemc_to_litter(:),&
    !$acc& this_type%m_livestemc_storage_to_litter(:),&
    !$acc& this_type%m_livestemc_xfer_to_litter(:),&
    !$acc& this_type%m_deadstemc_to_litter(:),&
    !$acc& this_type%m_deadstemc_storage_to_litter(:),&
    !$acc& this_type%m_deadstemc_xfer_to_litter(:),&
    !$acc& this_type%m_livecrootc_to_litter(:),&
    !$acc& this_type%m_livecrootc_storage_to_litter(:),&
    !$acc& this_type%m_livecrootc_xfer_to_litter(:),&
    !$acc& this_type%m_deadcrootc_to_litter(:),&
    !$acc& this_type%m_deadcrootc_storage_to_litter(:),&
    !$acc& this_type%m_deadcrootc_xfer_to_litter(:),&
    !$acc& this_type%m_gresp_storage_to_litter(:),&
    !$acc& this_type%m_gresp_xfer_to_litter(:),&
    !$acc& this_type%m_cpool_to_litter(:),&
    !$acc& this_type%hrv_leafc_to_litter(:),&
    !$acc& this_type%hrv_leafc_storage_to_litter(:),&
    !$acc& this_type%hrv_leafc_xfer_to_litter(:),&
    !$acc& this_type%hrv_frootc_to_litter(:),&
    !$acc& this_type%hrv_frootc_storage_to_litter(:),&
    !$acc& this_type%hrv_frootc_xfer_to_litter(:),&
    !$acc& this_type%hrv_livestemc_to_litter(:),&
    !$acc& this_type%hrv_livestemc_storage_to_litter(:),&
    !$acc& this_type%hrv_livestemc_xfer_to_litter(:),&
    !$acc& this_type%hrv_deadstemc_to_prod10c(:),&
    !$acc& this_type%hrv_deadstemc_to_prod100c(:),&
    !$acc& this_type%hrv_deadstemc_storage_to_litter(:),&
    !$acc& this_type%hrv_deadstemc_xfer_to_litter(:),&
    !$acc& this_type%hrv_livecrootc_to_litter(:),&
    !$acc& this_type%hrv_livecrootc_storage_to_litter(:),&
    !$acc& this_type%hrv_livecrootc_xfer_to_litter(:),&
    !$acc& this_type%hrv_deadcrootc_to_litter(:),&
    !$acc& this_type%hrv_deadcrootc_storage_to_litter(:),&
    !$acc& this_type%hrv_deadcrootc_xfer_to_litter(:),&
    !$acc& this_type%hrv_gresp_storage_to_litter(:),&
    !$acc& this_type%hrv_gresp_xfer_to_litter(:),&
    !$acc& this_type%hrv_xsmrpool_to_atm(:),&
    !$acc& this_type%hrv_cpool_to_litter(:),&
    !$acc& this_type%hrv_leafc_to_prod1c(:),&
    !$acc& this_type%hrv_livestemc_to_prod1c(:),&
    !$acc& this_type%hrv_grainc_to_prod1c(:),&
    !$acc& this_type%hrv_cropc_to_prod1c(:),&
    !$acc& this_type%m_leafc_to_fire(:),&
    !$acc& this_type%m_leafc_storage_to_fire(:),&
    !$acc& this_type%m_leafc_xfer_to_fire(:),&
    !$acc& this_type%m_livestemc_to_fire(:),&
    !$acc& this_type%m_livestemc_storage_to_fire(:),&
    !$acc& this_type%m_livestemc_xfer_to_fire(:),&
    !$acc& this_type%m_deadstemc_to_fire(:),&
    !$acc& this_type%m_deadstemc_storage_to_fire(:),&
    !$acc& this_type%m_deadstemc_xfer_to_fire(:),&
    !$acc& this_type%m_frootc_to_fire(:),&
    !$acc& this_type%m_frootc_storage_to_fire(:),&
    !$acc& this_type%m_frootc_xfer_to_fire(:),&
    !$acc& this_type%m_livecrootc_to_fire(:),&
    !$acc& this_type%m_livecrootc_storage_to_fire(:),&
    !$acc& this_type%m_livecrootc_xfer_to_fire(:),&
    !$acc& this_type%m_deadcrootc_to_fire(:),&
    !$acc& this_type%m_deadcrootc_storage_to_fire(:),&
    !$acc& this_type%m_deadcrootc_xfer_to_fire(:),&
    !$acc& this_type%m_gresp_storage_to_fire(:),&
    !$acc& this_type%m_gresp_xfer_to_fire(:),&
    !$acc& this_type%m_cpool_to_fire(:),&
    !$acc& this_type%m_leafc_to_litter_fire(:),&
    !$acc& this_type%m_leafc_storage_to_litter_fire(:),&
    !$acc& this_type%m_leafc_xfer_to_litter_fire(:),&
    !$acc& this_type%m_livestemc_to_litter_fire(:),&
    !$acc& this_type%m_livestemc_storage_to_litter_fire(:),&
    !$acc& this_type%m_livestemc_xfer_to_litter_fire(:),&
    !$acc& this_type%m_livestemc_to_deadstemc_fire(:),&
    !$acc& this_type%m_deadstemc_to_litter_fire(:),&
    !$acc& this_type%m_deadstemc_storage_to_litter_fire(:),&
    !$acc& this_type%m_deadstemc_xfer_to_litter_fire(:),&
    !$acc& this_type%m_frootc_to_litter_fire(:),&
    !$acc& this_type%m_frootc_storage_to_litter_fire(:),&
    !$acc& this_type%m_frootc_xfer_to_litter_fire(:),&
    !$acc& this_type%m_livecrootc_to_litter_fire(:),&
    !$acc& this_type%m_livecrootc_storage_to_litter_fire(:),&
    !$acc& this_type%m_livecrootc_xfer_to_litter_fire(:),&
    !$acc& this_type%m_livecrootc_to_deadcrootc_fire(:),&
    !$acc& this_type%m_deadcrootc_to_litter_fire(:),&
    !$acc& this_type%m_deadcrootc_storage_to_litter_fire(:),&
    !$acc& this_type%m_deadcrootc_xfer_to_litter_fire(:),&
    !$acc& this_type%m_gresp_storage_to_litter_fire(:),&
    !$acc& this_type%m_gresp_xfer_to_litter_fire(:),&
    !$acc& this_type%m_cpool_to_litter_fire(:),&
    !$acc& this_type%grainc_xfer_to_grainc(:),&
    !$acc& this_type%leafc_xfer_to_leafc(:),&
    !$acc& this_type%frootc_xfer_to_frootc(:),&
    !$acc& this_type%livestemc_xfer_to_livestemc(:),&
    !$acc& this_type%deadstemc_xfer_to_deadstemc(:),&
    !$acc& this_type%livecrootc_xfer_to_livecrootc(:),&
    !$acc& this_type%deadcrootc_xfer_to_deadcrootc(:),&
    !$acc& this_type%leafc_to_litter(:),&
    !$acc& this_type%frootc_to_litter(:),&
    !$acc& this_type%livestemc_to_litter(:),&
    !$acc& this_type%grainc_to_food(:),&
    !$acc& this_type%leaf_mr(:),&
    !$acc& this_type%froot_mr(:),&
    !$acc& this_type%livestem_mr(:),&
    !$acc& this_type%livecroot_mr(:),&
    !$acc& this_type%grain_mr(:),&
    !$acc& this_type%leaf_curmr(:),&
    !$acc& this_type%froot_curmr(:),&
    !$acc& this_type%livestem_curmr(:),&
    !$acc& this_type%livecroot_curmr(:),&
    !$acc& this_type%grain_curmr(:),&
    !$acc& this_type%leaf_xsmr(:),&
    !$acc& this_type%froot_xsmr(:),&
    !$acc& this_type%livestem_xsmr(:),&
    !$acc& this_type%livecroot_xsmr(:),&
    !$acc& this_type%grain_xsmr(:),&
    !$acc& this_type%xr(:),&
    !$acc& this_type%psnsun_to_cpool(:),&
    !$acc& this_type%psnshade_to_cpool(:),&
    !$acc& this_type%cpool_to_xsmrpool(:),&
    !$acc& this_type%cpool_to_grainc(:),&
    !$acc& this_type%cpool_to_grainc_storage(:),&
    !$acc& this_type%cpool_to_leafc(:),&
    !$acc& this_type%cpool_to_leafc_storage(:),&
    !$acc& this_type%cpool_to_frootc(:),&
    !$acc& this_type%cpool_to_frootc_storage(:),&
    !$acc& this_type%cpool_to_livestemc(:),&
    !$acc& this_type%cpool_to_livestemc_storage(:),&
    !$acc& this_type%cpool_to_deadstemc(:),&
    !$acc& this_type%cpool_to_deadstemc_storage(:),&
    !$acc& this_type%cpool_to_livecrootc(:),&
    !$acc& this_type%cpool_to_livecrootc_storage(:),&
    !$acc& this_type%cpool_to_deadcrootc(:),&
    !$acc& this_type%cpool_to_deadcrootc_storage(:),&
    !$acc& this_type%cpool_to_gresp_storage(:),&
    !$acc& this_type%xsmrpool_to_atm(:),&
    !$acc& this_type%cpool_leaf_gr(:),&
    !$acc& this_type%cpool_leaf_storage_gr(:),&
    !$acc& this_type%transfer_leaf_gr(:),&
    !$acc& this_type%cpool_froot_gr(:),&
    !$acc& this_type%cpool_froot_storage_gr(:),&
    !$acc& this_type%transfer_froot_gr(:),&
    !$acc& this_type%cpool_livestem_gr(:),&
    !$acc& this_type%cpool_livestem_storage_gr(:),&
    !$acc& this_type%transfer_livestem_gr(:),&
    !$acc& this_type%cpool_deadstem_gr(:),&
    !$acc& this_type%cpool_deadstem_storage_gr(:),&
    !$acc& this_type%transfer_deadstem_gr(:),&
    !$acc& this_type%cpool_livecroot_gr(:),&
    !$acc& this_type%cpool_livecroot_storage_gr(:),&
    !$acc& this_type%transfer_livecroot_gr(:),&
    !$acc& this_type%cpool_deadcroot_gr(:),&
    !$acc& this_type%cpool_deadcroot_storage_gr(:),&
    !$acc& this_type%transfer_deadcroot_gr(:),&
    !$acc& this_type%cpool_grain_gr(:),&
    !$acc& this_type%cpool_grain_storage_gr(:),&
    !$acc& this_type%transfer_grain_gr(:),&
    !$acc& this_type%grainc_storage_to_xfer(:),&
    !$acc& this_type%leafc_storage_to_xfer(:),&
    !$acc& this_type%frootc_storage_to_xfer(:),&
    !$acc& this_type%livestemc_storage_to_xfer(:),&
    !$acc& this_type%deadstemc_storage_to_xfer(:),&
    !$acc& this_type%livecrootc_storage_to_xfer(:),&
    !$acc& this_type%deadcrootc_storage_to_xfer(:),&
    !$acc& this_type%gresp_storage_to_xfer(:),&
    !$acc& this_type%livestemc_to_deadstemc(:),&
    !$acc& this_type%livecrootc_to_deadcrootc(:),&
    !$acc& this_type%gpp(:),&
    !$acc& this_type%gpp_before_downreg(:),&
    !$acc& this_type%mr(:),&
    !$acc& this_type%current_gr(:),&
    !$acc& this_type%transfer_gr(:),&
    !$acc& this_type%storage_gr(:),&
    !$acc& this_type%gr(:),&
    !$acc& this_type%ar(:),&
    !$acc& this_type%rr(:),&
    !$acc& this_type%npp(:),&
    !$acc& this_type%agnpp(:),&
    !$acc& this_type%bgnpp(:),&
    !$acc& this_type%litfall(:),&
    !$acc& this_type%vegfire(:),&
    !$acc& this_type%wood_harvestc(:),&
    !$acc& this_type%cinputs(:),&
    !$acc& this_type%coutputs(:),&
    !$acc& this_type%plant_calloc(:),&
    !$acc& this_type%excess_cflux(:),&
    !$acc& this_type%prev_leafc_to_litter(:),&
    !$acc& this_type%prev_frootc_to_litter(:),&
    !$acc& this_type%availc(:),&
    !$acc& this_type%xsmrpool_recover(:),&
    !$acc& this_type%xsmrpool_c13ratio(:),&
    !$acc& this_type%xsmrpool_turnover(:),&
    !$acc& this_type%frootc_alloc(:),&
    !$acc& this_type%frootc_loss(:),&
    !$acc& this_type%leafc_alloc(:),&
    !$acc& this_type%leafc_loss(:),&
    !$acc& this_type%woodc_alloc(:),&
    !$acc& this_type%woodc_loss(:),&
    !$acc& this_type%fire_closs(:),&
    !$acc& this_type%crop_seedc_to_leaf(:),&
    !$acc& this_type%dwt_seedc_to_leaf(:),&
    !$acc& this_type%dwt_seedc_to_deadstem(:),&
    !$acc& this_type%dwt_conv_cflux(:),&
    !$acc& this_type%dwt_prod10c_gain(:),&
    !$acc& this_type%dwt_prod100c_gain(:),&
    !$acc& this_type%dwt_crop_productc_gain(:),&
    !$acc& this_type%tempsum_npp(:),&
    !$acc& this_type%annsum_npp(:),&
    !$acc& this_type%annavg_agnpp(:),&
    !$acc& this_type%annavg_bgnpp(:),&
    !$acc& this_type%tempavg_agnpp(:),&
    !$acc& this_type%tempavg_bgnpp(:),&
    !$acc& this_type%agwdnpp(:),&
    !$acc& this_type%allocation_leaf(:),&
    !$acc& this_type%allocation_stem(:),&
    !$acc& this_type%allocation_froot(:))
  end subroutine deepcopy_vegetation_carbon_flux
  subroutine deepcopy_vegetation_nitrogen_flux(this_type)
    type(vegetation_nitrogen_flux), intent(inout) :: this_type
    !$acc enter data copyin(this_type)
    !$acc enter data copyin(&
    !$acc& this_type%m_leafn_to_litter(:),&
    !$acc& this_type%m_frootn_to_litter(:),&
    !$acc& this_type%m_leafn_storage_to_litter(:),&
    !$acc& this_type%m_frootn_storage_to_litter(:),&
    !$acc& this_type%m_livestemn_storage_to_litter(:),&
    !$acc& this_type%m_deadstemn_storage_to_litter(:),&
    !$acc& this_type%m_livecrootn_storage_to_litter(:),&
    !$acc& this_type%m_deadcrootn_storage_to_litter(:),&
    !$acc& this_type%m_leafn_xfer_to_litter(:),&
    !$acc& this_type%m_frootn_xfer_to_litter(:),&
    !$acc& this_type%m_livestemn_xfer_to_litter(:),&
    !$acc& this_type%m_deadstemn_xfer_to_litter(:),&
    !$acc& this_type%m_livecrootn_xfer_to_litter(:),&
    !$acc& this_type%m_deadcrootn_xfer_to_litter(:),&
    !$acc& this_type%m_livestemn_to_litter(:),&
    !$acc& this_type%m_deadstemn_to_litter(:),&
    !$acc& this_type%m_livecrootn_to_litter(:),&
    !$acc& this_type%m_deadcrootn_to_litter(:),&
    !$acc& this_type%m_retransn_to_litter(:),&
    !$acc& this_type%m_npool_to_litter(:),&
    !$acc& this_type%hrv_leafn_to_litter(:),&
    !$acc& this_type%hrv_frootn_to_litter(:),&
    !$acc& this_type%hrv_leafn_storage_to_litter(:),&
    !$acc& this_type%hrv_frootn_storage_to_litter(:),&
    !$acc& this_type%hrv_livestemn_storage_to_litter(:),&
    !$acc& this_type%hrv_deadstemn_storage_to_litter(:),&
    !$acc& this_type%hrv_livecrootn_storage_to_litter(:),&
    !$acc& this_type%hrv_deadcrootn_storage_to_litter(:),&
    !$acc& this_type%hrv_leafn_xfer_to_litter(:),&
    !$acc& this_type%hrv_frootn_xfer_to_litter(:),&
    !$acc& this_type%hrv_livestemn_xfer_to_litter(:),&
    !$acc& this_type%hrv_deadstemn_xfer_to_litter(:),&
    !$acc& this_type%hrv_livecrootn_xfer_to_litter(:),&
    !$acc& this_type%hrv_deadcrootn_xfer_to_litter(:),&
    !$acc& this_type%hrv_livestemn_to_litter(:),&
    !$acc& this_type%hrv_deadstemn_to_prod10n(:),&
    !$acc& this_type%hrv_deadstemn_to_prod100n(:),&
    !$acc& this_type%hrv_leafn_to_prod1n(:),&
    !$acc& this_type%hrv_livestemn_to_prod1n(:),&
    !$acc& this_type%hrv_grainn_to_prod1n(:),&
    !$acc& this_type%hrv_cropn_to_prod1n(:),&
    !$acc& this_type%hrv_livecrootn_to_litter(:),&
    !$acc& this_type%hrv_deadcrootn_to_litter(:),&
    !$acc& this_type%hrv_retransn_to_litter(:),&
    !$acc& this_type%hrv_npool_to_litter(:),&
    !$acc& this_type%m_leafn_to_fire(:),&
    !$acc& this_type%m_leafn_storage_to_fire(:),&
    !$acc& this_type%m_leafn_xfer_to_fire(:),&
    !$acc& this_type%m_livestemn_to_fire(:),&
    !$acc& this_type%m_livestemn_storage_to_fire(:),&
    !$acc& this_type%m_livestemn_xfer_to_fire(:),&
    !$acc& this_type%m_deadstemn_to_fire(:),&
    !$acc& this_type%m_deadstemn_storage_to_fire(:),&
    !$acc& this_type%m_deadstemn_xfer_to_fire(:),&
    !$acc& this_type%m_frootn_to_fire(:),&
    !$acc& this_type%m_frootn_storage_to_fire(:),&
    !$acc& this_type%m_frootn_xfer_to_fire(:),&
    !$acc& this_type%m_livecrootn_to_fire(:),&
    !$acc& this_type%m_livecrootn_storage_to_fire(:),&
    !$acc& this_type%m_livecrootn_xfer_to_fire(:),&
    !$acc& this_type%m_deadcrootn_to_fire(:),&
    !$acc& this_type%m_deadcrootn_storage_to_fire(:),&
    !$acc& this_type%m_deadcrootn_xfer_to_fire(:),&
    !$acc& this_type%m_retransn_to_fire(:),&
    !$acc& this_type%m_npool_to_fire(:),&
    !$acc& this_type%m_leafn_to_litter_fire(:),&
    !$acc& this_type%m_leafn_storage_to_litter_fire(:),&
    !$acc& this_type%m_leafn_xfer_to_litter_fire(:),&
    !$acc& this_type%m_livestemn_to_litter_fire(:),&
    !$acc& this_type%m_livestemn_storage_to_litter_fire(:),&
    !$acc& this_type%m_livestemn_xfer_to_litter_fire(:),&
    !$acc& this_type%m_livestemn_to_deadstemn_fire(:),&
    !$acc& this_type%m_deadstemn_to_litter_fire(:),&
    !$acc& this_type%m_deadstemn_storage_to_litter_fire(:),&
    !$acc& this_type%m_deadstemn_xfer_to_litter_fire(:),&
    !$acc& this_type%m_frootn_to_litter_fire(:),&
    !$acc& this_type%m_frootn_storage_to_litter_fire(:),&
    !$acc& this_type%m_frootn_xfer_to_litter_fire(:),&
    !$acc& this_type%m_livecrootn_to_litter_fire(:),&
    !$acc& this_type%m_livecrootn_storage_to_litter_fire(:),&
    !$acc& this_type%m_livecrootn_xfer_to_litter_fire(:),&
    !$acc& this_type%m_livecrootn_to_deadcrootn_fire(:),&
    !$acc& this_type%m_deadcrootn_to_litter_fire(:),&
    !$acc& this_type%m_deadcrootn_storage_to_litter_fire(:),&
    !$acc& this_type%m_deadcrootn_xfer_to_litter_fire(:),&
    !$acc& this_type%m_retransn_to_litter_fire(:),&
    !$acc& this_type%m_npool_to_litter_fire(:),&
    !$acc& this_type%leafn_xfer_to_leafn(:),&
    !$acc& this_type%frootn_xfer_to_frootn(:),&
    !$acc& this_type%livestemn_xfer_to_livestemn(:),&
    !$acc& this_type%deadstemn_xfer_to_deadstemn(:),&
    !$acc& this_type%livecrootn_xfer_to_livecrootn(:),&
    !$acc& this_type%deadcrootn_xfer_to_deadcrootn(:),&
    !$acc& this_type%leafn_to_litter(:),&
    !$acc& this_type%leafn_to_retransn(:),&
    !$acc& this_type%frootn_to_retransn(:),&
    !$acc& this_type%frootn_to_litter(:),&
    !$acc& this_type%retransn_to_npool(:),&
    !$acc& this_type%sminn_to_npool(:),&
    !$acc& this_type%npool_to_leafn(:),&
    !$acc& this_type%npool_to_leafn_storage(:),&
    !$acc& this_type%npool_to_frootn(:),&
    !$acc& this_type%npool_to_frootn_storage(:),&
    !$acc& this_type%npool_to_livestemn(:),&
    !$acc& this_type%npool_to_livestemn_storage(:),&
    !$acc& this_type%npool_to_deadstemn(:),&
    !$acc& this_type%npool_to_deadstemn_storage(:),&
    !$acc& this_type%npool_to_livecrootn(:),&
    !$acc& this_type%npool_to_livecrootn_storage(:),&
    !$acc& this_type%npool_to_deadcrootn(:),&
    !$acc& this_type%npool_to_deadcrootn_storage(:),&
    !$acc& this_type%leafn_storage_to_xfer(:),&
    !$acc& this_type%frootn_storage_to_xfer(:),&
    !$acc& this_type%livestemn_storage_to_xfer(:),&
    !$acc& this_type%deadstemn_storage_to_xfer(:),&
    !$acc& this_type%livecrootn_storage_to_xfer(:),&
    !$acc& this_type%deadcrootn_storage_to_xfer(:),&
    !$acc& this_type%livestemn_to_deadstemn(:),&
    !$acc& this_type%livestemn_to_retransn(:),&
    !$acc& this_type%livecrootn_to_deadcrootn(:),&
    !$acc& this_type%livecrootn_to_retransn(:),&
    !$acc& this_type%ndeploy(:),&
    !$acc& this_type%wood_harvestn(:),&
    !$acc& this_type%fire_nloss(:),&
    !$acc& this_type%npool_to_grainn(:),&
    !$acc& this_type%npool_to_grainn_storage(:),&
    !$acc& this_type%livestemn_to_litter(:),&
    !$acc& this_type%grainn_to_food(:),&
    !$acc& this_type%grainn_xfer_to_grainn(:),&
    !$acc& this_type%grainn_storage_to_xfer(:),&
    !$acc& this_type%fert(:),&
    !$acc& this_type%fert_counter(:),&
    !$acc& this_type%soyfixn(:),&
    !$acc& this_type%nfix_to_plantn(:),&
    !$acc& this_type%crop_seedn_to_leaf(:),&
    !$acc& this_type%dwt_seedn_to_leaf(:),&
    !$acc& this_type%dwt_seedn_to_deadstem(:),&
    !$acc& this_type%dwt_conv_nflux(:),&
    !$acc& this_type%dwt_prod10n_gain(:),&
    !$acc& this_type%dwt_prod100n_gain(:),&
    !$acc& this_type%dwt_crop_productn_gain(:),&
    !$acc& this_type%dwt_seedn_to_npool(:),&
    !$acc& this_type%plant_ndemand(:),&
    !$acc& this_type%avail_retransn(:),&
    !$acc& this_type%plant_nalloc(:),&
    !$acc& this_type%smin_no3_to_plant(:),&
    !$acc& this_type%smin_nh4_to_plant(:),&
    !$acc& this_type%sminn_to_plant(:),&
    !$acc& this_type%plant_nh4demand_vr(:,:),&
    !$acc& this_type%plant_no3demand_vr(:,:),&
    !$acc& this_type%plant_ndemand_vr(:,:),&
    !$acc& this_type%prev_leafn_to_litter(:),&
    !$acc& this_type%prev_frootn_to_litter(:),&
    !$acc& this_type%supplement_to_plantn(:),&
    !$acc& this_type%gap_nloss_litter(:),&
    !$acc& this_type%fire_nloss_litter(:),&
    !$acc& this_type%hrv_nloss_litter(:),&
    !$acc& this_type%sen_nloss_litter(:))
  end subroutine deepcopy_vegetation_nitrogen_flux
end module DeepCopyVegetationMod
