if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_SLASHPROC")
endif()
string(APPEND CMAKE_Fortran_FLAGS_RELEASE " -qno-opt-dynamic-align")
if (MPILIB STREQUAL impi)
  set(MPICC "mpiicc")
endif()
if (MPILIB STREQUAL impi)
  set(MPICXX "mpiicpc")
endif()
if (MPILIB STREQUAL impi)
  set(MPIFC "mpiifort")
endif()
