set(PIO_FILESYSTEM_HINTS "lustre")
if (MPILIB STREQUAL impi)
  set(MPICC "mpiicc")
endif()
if (MPILIB STREQUAL impi)
  set(MPICXX "mpiicpc")
endif()
if (MPILIB STREQUAL impi)
  set(MPIFC "mpiifort")
endif()
if (NOT MPILIB STREQUAL impi)
  set(MPICC "mpicc")
endif()
if (NOT MPILIB STREQUAL impi)
  set(MPICXX "mpic++")
endif()
string(APPEND CMAKE_EXE_LINKER_FLAGS " -lpthread")
