name: elm-tests

on:
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        test:
          - SMS_Ly1.ELM_USRDAT.I1850uELMCNPRDCTCBC.ghci-oci_gnu.elm-kilocraft
    runs-on: ubuntu-latest
    container:
      image: schwartzpd/elm-ghci:latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
          submodules: recursive
      - 
        name: CIME
        working-directory: cime/scripts
        run: |
          ./create_test ${{ matrix.test }} --wait --debug
      - 
        name: Artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: ${{ matrix.test }}
          path: |
            /projects/e3sm/scratch/${{ matrix.test }}*/TestStatus.log
            /projects/e3sm/scratch/${{ matrix.test }}*/bld/*.bldlog.*
            /projects/e3sm/scratch/${{ matrix.test }}*/run/*.log.*
            /projects/e3sm/scratch/${{ matrix.test }}*/run/*.cprnc.out

